const API_BASE=document.querySelector('meta[name="api-base"]').content;
const apiToken=()=>localStorage.getItem('ag_token')||sessionStorage.getItem('ag_token');
function apiError(data){if(data.detail)return data.detail;const walk=value=>Array.isArray(value)?value.map(walk).join(' '):value&&typeof value==='object'?Object.entries(value).map(([key,val])=>`${key}: ${walk(val)}`).join(' '):String(value);return walk(data)||'Request failed.'}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(apiToken())headers.Authorization=`Token ${apiToken()}`;const response=await fetch(`${API_BASE}${path}`,{...options,headers});if(response.status===204)return null;const data=await response.json().catch(()=>({detail:'Request failed.'}));if(response.status===401&&!path.startsWith('/auth/login')){localStorage.removeItem('ag_token');sessionStorage.removeItem('ag_token');localStorage.removeItem('if_session');sessionStorage.removeItem('if_session');showAuth('login');throw new Error('Session expired. Please sign in again.')}if(!response.ok)throw new Error(apiError(data));return data}
const listResults=data=>Array.isArray(data)?data:(data.results||[]);
const mapCustomer=c=>({id:String(c.id),name:c.name,email:c.email,phone:c.phone,tax:c.ntn_strn,address:c.address,notes:c.notes});
const mapInvoice=i=>({id:String(i.id),number:i.number,issueDate:i.issue_date,dueDate:i.due_date,invoiceType:i.invoice_type,taxType:i.tax_type||'PST',fbrStatus:i.fbr_status,fbrNumber:i.fbr_invoice_number,fbrError:i.fbr_error,invoicePeriod:i.invoice_period,contractName:i.contract_name,status:{DRAFT:'Draft',SENT:'Sent',PAID:'Paid',PARTIAL:'Partially Paid',OVERDUE:'Overdue',CANCELLED:'Cancelled'}[i.status]||i.status,customer:{id:String(i.customer),name:i.customer_name},items:i.items.map(x=>({description:x.description,months:+(x.months||1),qty:+x.quantity,rate:+x.unit_price,service:+x.service_charge,tax:+x.tax_rate})),subtotal:+i.subtotal,tax:+i.tax_total,discount:+i.discount,total:+i.total,notes:i.notes,createdAt:i.created_at});
const mapQuote=q=>({id:String(q.id),number:q.number,date:q.issue_date,validUntil:q.valid_until,status:{DRAFT:'Draft',SENT:'Sent',ACCEPTED:'Accepted',REJECTED:'Rejected',EXPIRED:'Expired'}[q.status]||q.status,customer:{id:String(q.customer),name:q.customer_name},category:q.items[0]?.category||'',description:q.items[0]?.description||'',amount:+q.subtotal,taxRate:+(q.items[0]?.tax_rate||0),tax:+q.tax_total,total:+q.total,terms:q.notes});
async function loadPhaseOne(){if(!apiToken())return;try{const staff=getSession()?.role==='Employee', [cs,qs,ins]=await Promise.all([api('/customers/'),api('/quotations/'),staff?Promise.resolve([]):api('/invoices/')]);customers=listResults(cs).map(mapCustomer);quotations=listResults(qs).map(mapQuote);invoices=listResults(ins).map(mapInvoice);renderAll()}catch(error){toast(error.message)}}
async function loadUsers(){if(getSession()?.role!=='Admin')return;try{const data=await api('/users/');const rows=listResults(data);$('#user-table').innerHTML=`<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${escapeHtml(`${u.first_name||''} ${u.last_name||''}`.trim()||u.username)}</td><td>${escapeHtml(u.email)}</td><td>${u.role}</td><td>${escapeHtml(u.department||'-')}</td><td><span class="badge ${u.is_active?'paid':''}">${u.is_active?'Active':'Disabled'}</span></td><td class="actions"><button onclick="toggleUser('${u.id}',${!u.is_active})">${u.is_active?'Disable':'Activate'}</button></td></tr>`).join('')}</tbody></table>`}catch(error){toast(error.message)}}
async function loadFBRSettings(){if(getSession()?.role!=='Admin')return;try{const s=await api('/fbr/settings/');const values={'fbr-business-name':s.business_name||company.name||'Ample Global Enterprises Pvt Ltd','fbr-seller-ntn':s.seller_ntn||'','fbr-seller-strn':s.seller_strn||'','fbr-province':s.province||'Punjab','fbr-address':s.registered_address||company.address||'','fbr-bpos-id':s.bpos_id||'','fbr-environment':s.environment||'SANDBOX','fbr-sale-type':s.sale_type||'T1000018','fbr-hs-code':s.default_hs_code||'','fbr-product-code':s.default_product_code||'','fbr-uom':s.default_uom||'U1000003'};Object.entries(values).forEach(([id,value])=>{if($(`#${id}`))$(`#${id}`).value=value});$('#fbr-readiness').innerHTML=`<p><strong>Settings:</strong> ${s.configured?'Saved':'Incomplete'}</p><p><strong>API token:</strong> ${s.token_configured?'Configured securely':'Not configured'}</p><p><strong>Submission:</strong> ${s.submission_enabled?'Enabled':'Disabled (safe mode)'}</p><p><strong>Environment:</strong> ${s.environment||'Sandbox'}</p>`;await loadFBRLogs()}catch(error){toast(error.message)}}
async function loadFBRLogs(){if(getSession()?.role!=='Admin')return;try{const rows=await api('/fbr/logs/');$('#fbr-log-table').innerHTML=rows.length?`<table><thead><tr><th>Date/Time</th><th>Invoice</th><th>Action</th><th>Result</th><th>Message</th><th>User</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${escapeHtml(x.invoice_number)}</td><td>${x.action}</td><td><span class="badge ${x.result==='SUCCESS'?'paid':''}">${x.result}</span></td><td>${escapeHtml(x.error||x.response?.detail||'-')}</td><td>${escapeHtml(x.requested_by_email)}</td></tr>`).join('')}</tbody></table>`:'<div style="padding:24px;text-align:center" class="muted">No FBR activity yet.</div>'}catch(error){toast(error.message)}}
$('#login-form').onsubmit=async e=>{e.preventDefault();const msg=$('#login-error');msg.textContent='Signing in…';try{const result=await api('/auth/login/',{method:'POST',body:JSON.stringify({email:$('#login-email').value.trim(),password:$('#login-password').value})});const storage=$('#remember-me').checked?localStorage:sessionStorage;storage.setItem('ag_token',result.token);storage.setItem('if_session',JSON.stringify({email:result.user.email,name:result.user.first_name||result.user.email,role:{ADMIN:'Admin',STAFF:'Employee'}[result.user.role],department:result.user.department}));msg.textContent='';applySession();await Promise.all([loadPhaseOne(),loadUsers(),loadFBRSettings(),loadAccounting()]);toast('Secure login successful')}catch(error){msg.textContent=error.message}};
$('#password-change-form').onsubmit=async e=>{e.preventDefault();const next=$('#new-password').value;if(next!==$('#confirm-new-password').value)return toast('New passwords do not match');try{const result=await api('/auth/password-change/',{method:'POST',body:JSON.stringify({current_password:$('#current-password').value,new_password:next})});const storage=localStorage.getItem('ag_token')?localStorage:sessionStorage;storage.setItem('ag_token',result.token);e.target.reset();toast(result.detail)}catch(error){toast(error.message)}};
$('#add-user').onclick=()=>$('#user-dialog').showModal();
$('#user-form').onsubmit=async e=>{e.preventDefault();try{const email=$('#user-email').value.trim().toLowerCase();await api('/users/',{method:'POST',body:JSON.stringify({username:email,email,first_name:$('#user-name').value,department:$('#user-department').value,role:$('#user-role').value,is_active:true,password:$('#user-password').value})});e.target.reset();$('#user-dialog').close();await loadUsers();toast('Employee account created')}catch(error){toast(error.message)}};
window.toggleUser=async(id,is_active)=>{try{await api(`/users/${id}/`,{method:'PATCH',body:JSON.stringify({is_active})});await loadUsers();toast(is_active?'Employee activated':'Employee disabled')}catch(error){toast(error.message)}};
$('#fbr-settings-form').onsubmit=async e=>{e.preventDefault();try{await api('/fbr/settings/',{method:'PUT',body:JSON.stringify({business_name:$('#fbr-business-name').value,seller_ntn:$('#fbr-seller-ntn').value,seller_strn:$('#fbr-seller-strn').value,registered_address:$('#fbr-address').value,province:$('#fbr-province').value,bpos_id:$('#fbr-bpos-id').value,sale_type:$('#fbr-sale-type').value,default_hs_code:$('#fbr-hs-code').value,default_product_code:$('#fbr-product-code').value,default_uom:$('#fbr-uom').value,environment:$('#fbr-environment').value})});await loadFBRSettings();toast('FBR settings saved safely')}catch(error){toast(error.message)}};
$('#refresh-fbr-logs').onclick=loadFBRLogs;$('[data-view="fbr-settings"]').addEventListener('click',loadFBRSettings);
$('#register-form').onsubmit=async e=>{e.preventDefault();const msg=$('#register-message'),password=$('#register-password').value;if(password!==$('#register-confirm').value){msg.className='auth-message error';msg.textContent='Passwords do not match.';return}try{await api('/auth/register/',{method:'POST',body:JSON.stringify({name:$('#register-name').value,email:$('#register-email').value,department:$('#register-department').value,password})});msg.className='auth-message';msg.textContent='Account created. You can now sign in.';setTimeout(()=>showAuth('login'),900)}catch(error){msg.className='auth-message error';msg.textContent=error.message}};
$('#reset-form').onsubmit=async e=>{e.preventDefault();const msg=$('#reset-message');try{const result=await api('/auth/password-reset/',{method:'POST',body:JSON.stringify({email:$('#reset-email').value})});msg.className='auth-message';msg.textContent=result.detail}catch(error){msg.className='auth-message error';msg.textContent=error.message}};
$('#logout').onclick=async()=>{try{await api('/auth/logout/',{method:'POST'})}catch{}localStorage.removeItem('ag_token');sessionStorage.removeItem('ag_token');localStorage.removeItem('if_session');sessionStorage.removeItem('if_session');showAuth('login');applySession()};
$('#customer-form').onsubmit=async e=>{e.preventDefault();try{await api('/customers/',{method:'POST',body:JSON.stringify({name:$('#customer-name').value,email:$('#customer-email').value,phone:$('#customer-phone').value,ntn_strn:$('#customer-tax').value,address:$('#customer-address').value})});e.target.reset();dialog.close();await loadPhaseOne();toast('Customer saved to database')}catch(error){toast(error.message)}};
$('#invoice-form').onsubmit=async e=>{e.preventDefault();const customer=customers.find(c=>c.id===$('#customer-select').value);if(!customer)return toast('Please select a customer');const payload={number:$('#invoice-number').value,customer:+customer.id,issue_date:$('#issue-date').value,due_date:$('#due-date').value,invoice_type:$('#invoice-type').value,tax_type:$('#tax-type').value,invoice_period:$('#invoice-period').value,contract_name:$('#contract-name').value,status:{Unpaid:'SENT',Paid:'PAID','Partially Paid':'PARTIAL'}[$('#invoice-status').value]||'DRAFT',discount:String(calculate().discount),notes:$('#notes').value,items:$$('.item-row').map(r=>({description:r.querySelector('.desc').value,months:'1',quantity:r.querySelector('.qty').value,unit_price:r.querySelector('.rate').value,service_charge:r.querySelector('.service')?.value||'0',tax_rate:r.querySelector('.tax').value}))};if($('#invoice-revenue-account').value)payload.revenue_account=+$('#invoice-revenue-account').value;try{await api('/invoices/',{method:'POST',body:JSON.stringify(payload)});e.target.reset();$('#items').innerHTML='';updateTaxType();await Promise.all([loadPhaseOne(),loadAccounting()]);showView('invoices');toast(`${payload.tax_type} invoice and accounting entry saved`)}catch(error){toast(error.message)}};
$('#quotation-form').onsubmit=async e=>{e.preventDefault();const customer=customers.find(c=>c.id===$('#quote-customer').value);if(!customer)return toast('Please select a customer');const statusMap={Draft:'DRAFT',Sent:'SENT',Approved:'ACCEPTED',Rejected:'REJECTED'};const payload={number:$('#quote-number').value,customer:+customer.id,issue_date:$('#quote-date').value,valid_until:$('#quote-valid').value,status:statusMap[$('#quote-status').value]||'DRAFT',discount:'0',notes:$('#quote-terms').value,items:[{description:$('#quote-description').value,category:$('#quote-category').value,quantity:'1',unit_price:$('#quote-amount').value,tax_rate:$('#quote-tax').value}]};try{await api('/quotations/',{method:'POST',body:JSON.stringify(payload)});e.target.reset();quoteDialog.close();await loadPhaseOne();toast('Quotation saved to database')}catch(error){toast(error.message)}};
async function downloadDocument(type,id,number){try{const response=await fetch(`${API_BASE}/${type}/${id}/pdf/`,{headers:{Authorization:`Token ${apiToken()}`}});if(!response.ok)throw new Error('PDF download failed.');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${number}.pdf`;a.click();URL.revokeObjectURL(url)}catch(error){toast(error.message)}}
window.printInvoice=id=>{const i=invoices.find(x=>x.id===id);return downloadDocument('invoices',id,i.number)};
window.printQuotation=id=>{const q=quotations.find(x=>x.id===id);return downloadDocument('quotations',id,q.number)};
window.deleteInvoice=async id=>{if(confirm('Delete this invoice?')){await api(`/invoices/${id}/`,{method:'DELETE'});await loadPhaseOne();toast('Invoice deleted')}};
window.deleteQuotation=async id=>{if(confirm('Delete this quotation?')){await api(`/quotations/${id}/`,{method:'DELETE'});await loadPhaseOne();toast('Quotation deleted')}};
window.convertQuotation=async id=>{try{await api(`/quotations/${id}/convert/`,{method:'POST',body:'{}'});await loadPhaseOne();showView('invoices');toast('Quotation converted to invoice')}catch(error){toast(error.message)}};
async function emailDocument(type,id){try{const result=await api(`/${type}/${id}/email/`,{method:'POST',body:'{}'});toast(result.detail)}catch(error){toast(error.message)}}
table=data=>!data.length?'<div style="padding:28px;text-align:center;color:#6c768b">No invoices yet.</div>':`<table><thead><tr><th>Invoice</th><th>Type / FBR</th><th>Customer</th><th>Date</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>${data.map(i=>`<tr><td><strong>${escapeHtml(i.number)}</strong></td><td>${i.invoiceType==='FBR'?`FBR Sales Tax<br><span class="badge ${i.fbrStatus==='SUBMITTED'?'paid':''}">${escapeHtml(i.fbrStatus)}</span>`:i.invoiceType==='NORMAL'?'Normal':'HR / Payroll'}</td><td>${escapeHtml(i.customer.name)}</td><td>${i.issueDate}</td><td><span class="badge ${i.status.toLowerCase().replaceAll(' ','-')}">${i.status}</span></td><td><strong>${money(i.total)}</strong></td><td class="actions"><button onclick="printInvoice('${i.id}')">PDF</button><button onclick="emailDocument('invoices','${i.id}')">Email</button>${i.invoiceType==='FBR'?`<button onclick="validateFBR('${i.id}')">Validate FBR</button><button onclick="submitFBR('${i.id}')">Submit FBR</button>`:''}<button onclick="deleteInvoice('${i.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`;
window.validateFBR=async id=>{try{const result=await api(`/invoices/${id}/fbr_precheck/`,{method:'POST',body:'{}'});await loadPhaseOne();await loadFBRLogs();toast(result.detail)}catch(error){await loadPhaseOne();await loadFBRLogs();toast(error.message)}};
window.submitFBR=async id=>{const invoice=invoices.find(i=>String(i.id)===String(id));if(!invoice||invoice.invoiceType!=='FBR')return toast('Only FBR Sales Tax invoices can be submitted');if(!confirm(`Submit only invoice ${invoice.number} to FBR? This action will not include any HR or Normal invoice.`))return;try{const result=await api(`/invoices/${id}/submit_fbr/`,{method:'POST',body:'{}'});await loadPhaseOne();toast(result.detail)}catch(error){toast(error.message)}};

let accountingAccounts=[],accountingJournals=[],accountingTrial=null,accountingPL=null,accountingBalance=null;
const accountingRows=data=>listResults(data);
function accountLabel(row){return `${escapeHtml(row.code)} — ${escapeHtml(row.name)}`}
function renderAccounting(tab='coa'){
  const content=$('#accounting-content');if(!content)return;
  $$('.account-tab').forEach(button=>button.classList.toggle('active',button.dataset.accountTab===tab));
  const titles={coa:['Chart of Accounts','Complete Ample Global account hierarchy.'],journal:['Journal Entries','Automatic and manual double-entry transactions.'],trial:['Trial Balance','Total debits must always equal total credits.'],pl:['Profit & Loss','Accrual-basis income and expenses.'],balance:['Balance Sheet','Assets, liabilities and equity position.']};$('#accounting-title').textContent=titles[tab][0];$('#accounting-subtitle').textContent=titles[tab][1];
  if(tab==='coa')content.innerHTML=`<table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Parent</th><th>Status</th><th>Action</th></tr></thead><tbody>${accountingAccounts.map(a=>`<tr class="${a.account_type==='HEADER'?'account-type-row':''}"><td>${escapeHtml(a.code)}</td><td>${escapeHtml(a.name)}</td><td>${escapeHtml(a.account_type.replaceAll('_',' '))}</td><td>${escapeHtml(a.parent_name||'-')}</td><td><span class="badge ${a.is_active?'paid':''}">${a.is_active?'Active':'Disabled'}</span></td><td><button onclick="viewLedger('${a.id}')">Ledger</button> <button onclick="toggleAccount('${a.id}',${!a.is_active})">${a.is_active?'Disable':'Activate'}</button></td></tr>`).join('')}</tbody></table>`;
  if(tab==='journal')content.innerHTML=accountingJournals.length?`<table><thead><tr><th>Date</th><th>Entry</th><th>Source</th><th>Memo</th><th>Reference</th><th>Debit</th><th>Credit</th></tr></thead><tbody>${accountingJournals.map(j=>`<tr><td>${j.entry_date}</td><td>${escapeHtml(j.entry_number)}</td><td>${j.source_type}</td><td>${escapeHtml(j.memo)}</td><td>${escapeHtml(j.reference||'-')}</td><td>${money(j.total_debit)}</td><td>${money(j.total_credit)}</td></tr><tr><td></td><td colspan="6"><small>${j.lines.map(l=>`${escapeHtml(l.account_code)} ${escapeHtml(l.account_name)}: Dr ${money(l.debit)} / Cr ${money(l.credit)}`).join('<br>')}</small></td></tr>`).join('')}</tbody></table>`:'<p class="muted">No journal entries yet.</p>';
  if(tab==='trial'){const t=accountingTrial||{rows:[],total_debit:0,total_credit:0,balanced:true};content.innerHTML=`<table><thead><tr><th>Code</th><th>Account</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${t.rows.map(r=>`<tr><td>${r.account__code}</td><td>${escapeHtml(r.account__name)}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td><td>${money(r.balance)}</td></tr>`).join('')}<tr><th colspan="2">TOTAL</th><th>${money(t.total_debit)}</th><th>${money(t.total_credit)}</th><th>${t.balanced?'BALANCED':'CHECK REQUIRED'}</th></tr></tbody></table>`}
  if(tab==='pl'){const p=accountingPL||{income:[],expenses:[],total_income:0,total_expenses:0,net_profit:0};content.innerHTML=`<table><thead><tr><th>Section</th><th>Code</th><th>Account</th><th>Amount</th></tr></thead><tbody>${p.income.map(r=>`<tr><td>Income</td><td>${r.account__code}</td><td>${escapeHtml(r.account__name)}</td><td>${money(r.amount)}</td></tr>`).join('')}${p.expenses.map(r=>`<tr><td>Expense</td><td>${r.account__code}</td><td>${escapeHtml(r.account__name)}</td><td>${money(r.amount)}</td></tr>`).join('')}<tr><th colspan="3">Net Profit / (Loss)</th><th>${money(p.net_profit)}</th></tr></tbody></table>`}
  if(tab==='balance'){const b=accountingBalance||{assets:[],liabilities:[],equity:[],current_earnings:0,total_assets:0,total_liabilities:0,total_equity:0};content.innerHTML=`<table><thead><tr><th>Section</th><th>Code</th><th>Account</th><th>Amount</th></tr></thead><tbody>${[['Asset',b.assets],['Liability',b.liabilities],['Equity',b.equity]].flatMap(([type,rows])=>rows.map(r=>`<tr><td>${type}</td><td>${r.account__code}</td><td>${escapeHtml(r.account__name)}</td><td>${money(r.amount)}</td></tr>`)).join('')}<tr><td>Equity</td><td>—</td><td>Current Year Profit / Loss</td><td>${money(b.current_earnings)}</td></tr><tr><th colspan="3">Total Assets</th><th>${money(b.total_assets)}</th></tr><tr><th colspan="3">Liabilities + Equity</th><th>${money(Number(b.total_liabilities)+Number(b.total_equity))} · ${b.balanced?'BALANCED':'REVIEW'}</th></tr></tbody></table>`}
}
async function loadAccounting(tab='coa'){if(getSession()?.role!=='Admin')return;try{const [accountsResult,journalsResult,trial,pl,balance]=await Promise.all([api('/accounts/'),api('/journal-entries/'),api('/accounting/trial-balance/'),api('/accounting/profit-loss/'),api('/accounting/balance-sheet/')]);accountingAccounts=accountingRows(accountsResult);accountingJournals=accountingRows(journalsResult);accountingTrial=trial;accountingPL=pl;accountingBalance=balance;$('#account-count').textContent=accountingAccounts.length;$('#journal-count').textContent=accountingJournals.length;$('#account-debit').textContent=money(trial.total_debit);$('#account-balance-status').textContent=trial.balanced?'Balanced':'Review';renderAccounting(tab);const active=accountingAccounts.filter(a=>a.is_active&&a.account_type!=='HEADER'),options=active.map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('');$('#journal-debit-account').innerHTML=options;$('#journal-credit-account').innerHTML=options;$('#invoice-revenue-account').innerHTML='<option value="">Automatic from service</option>'+active.filter(a=>['INCOME','CONTRA_INCOME'].includes(a.account_type)).map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('');$('#payment-deposit-account').innerHTML='<option value="">Automatic (Cash/Bank)</option>'+active.filter(a=>a.account_type==='ASSET').map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('');$('#expense-ledger-account').innerHTML='<option value="">Automatic from category</option>'+active.filter(a=>['EXPENSE','CONTRA_EXPENSE'].includes(a.account_type)).map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('');$('#expense-payment-account').innerHTML='<option value="">Automatic (Bank)</option>'+active.filter(a=>['ASSET','LIABILITY'].includes(a.account_type)).map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('');$('#account-parent').innerHTML='<option value="">None</option>'+accountingAccounts.map(a=>`<option value="${a.id}">${accountLabel(a)}</option>`).join('')}catch(error){toast(error.message)}}
$$('.account-tab').forEach(button=>button.onclick=()=>renderAccounting(button.dataset.accountTab));$('[data-view="accounting"]').addEventListener('click',()=>loadAccounting('coa'));
$('#add-journal').onclick=()=>{$('#journal-date').value=today();$('#journal-dialog').showModal()};$('#journal-form').onsubmit=async e=>{e.preventDefault();const amount=$('#journal-amount').value;try{await api('/journal-entries/',{method:'POST',body:JSON.stringify({entry_date:$('#journal-date').value,memo:$('#journal-memo').value,reference:$('#journal-reference').value,lines:[{account:+$('#journal-debit-account').value,debit:amount,credit:'0'},{account:+$('#journal-credit-account').value,debit:'0',credit:amount}]})});e.target.reset();$('#journal-dialog').close();await loadAccounting('journal');toast('Balanced journal entry posted')}catch(error){toast(error.message)}};
$('#add-account').onclick=()=>$('#account-dialog').showModal();$('#account-form').onsubmit=async e=>{e.preventDefault();const payload={code:$('#account-code').value.trim(),name:$('#account-name').value.trim(),account_type:$('#account-type').value,description:$('#account-description').value,is_active:true};if($('#account-parent').value)payload.parent=+$('#account-parent').value;try{await api('/accounts/',{method:'POST',body:JSON.stringify(payload)});e.target.reset();$('#account-dialog').close();await loadAccounting('coa');toast('Account added successfully')}catch(error){toast(error.message)}};window.toggleAccount=async(id,is_active)=>{try{await api(`/accounts/${id}/`,{method:'PATCH',body:JSON.stringify({is_active})});await loadAccounting('coa');toast(is_active?'Account activated':'Account disabled')}catch(error){toast(error.message)}};
window.viewLedger=async id=>{try{const result=await api(`/accounts/${id}/ledger/`);$('#accounting-title').textContent=`Ledger · ${result.account.code} ${result.account.name}`;$('#accounting-subtitle').textContent=`Closing balance: ${money(result.closing_balance)}`;$('#accounting-content').innerHTML=result.rows.length?`<table><thead><tr><th>Date</th><th>Entry</th><th>Memo</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${r.date}</td><td>${r.entry_number}</td><td>${escapeHtml(r.memo)}</td><td>${escapeHtml(r.reference||'-')}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td><td>${money(r.balance)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">No activity in this account.</p>'}catch(error){toast(error.message)}};
renderQuotations=()=>{$('#quotation-table').innerHTML=!quotations.length?'<div style="padding:28px;text-align:center;color:#6c768b">No quotations yet.</div>':`<table><thead><tr><th>Quotation</th><th>Customer</th><th>Service</th><th>Valid until</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>${quotations.map(q=>`<tr><td><strong>${escapeHtml(q.number)}</strong></td><td>${escapeHtml(q.customer.name)}</td><td>${escapeHtml(q.category)}</td><td>${q.validUntil}</td><td><span class="badge ${q.status.toLowerCase()}">${q.status}</span></td><td><strong>${money(q.total)}</strong></td><td class="actions"><button onclick="printQuotation('${q.id}')">PDF</button><button onclick="emailDocument('quotations','${q.id}')">Email</button><button onclick="convertQuotation('${q.id}')">Convert</button><button onclick="deleteQuotation('${q.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`};
if(apiToken()){const saved=localStorage.getItem('if_session')||sessionStorage.getItem('if_session');if(saved){applySession();loadPhaseOne();loadUsers();loadFBRSettings();loadAccounting()}}
