/* Ample Global v41: catalog, billing and FBR business modules */
Object.assign(titles,{
  'new-bill':['New Bill','Create and approve supplier bills'],bills:['Bills','Search and manage supplier bills'],
  'purchase-orders':['Purchase Orders','Manage supplier purchase orders'],'debit-notes':['Debit Notes','Manage supplier debit notes'],
  'recurring-bills':['Recurring Bills','Schedule repeat supplier bills'],'make-payments':['Make Payments','Record supplier payments'],
  'fbr-submit':['Submit Invoice','Select approved tax invoices for FBR'],'fbr-submitted':['Submitted Invoices','FBR submission history']
});

let catalogTab='product';
let catalogEntities=store.get('ag_catalog_entities',{department:[],manufacturer:[],region:[],category:[]});
let bills=store.get('ag_bills',[]),purchaseOrders=store.get('ag_purchase_orders',[]),debitNotes=store.get('ag_debit_notes',[]),recurringBills=store.get('ag_recurring_bills',[]),supplierPayments=store.get('ag_supplier_payments',[]);
let billingEntryType='purchase-order';
const catalogLabels={department:'Departments',manufacturer:'Manufacturers',region:'Regions',category:'Categories',product:'Products'};
const catalogSingular={department:'Department',manufacturer:'Manufacturer',region:'Region',category:'Category',product:'Product'};

function setCatalogTab(tab){catalogTab=tab;showView('catalog');renderCatalogV41()}
$$('[data-catalog-tab]').forEach(b=>b.onclick=()=>setCatalogTab(b.dataset.catalogTab));
$('#catalog-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b)setCatalogTab(b.dataset.tab)};

function fillCatalogSelects(){
  const make=(key,placeholder)=>`<option value="">${placeholder}</option>${catalogEntities[key].map(x=>`<option>${escapeHtml(x.name)}</option>`).join('')}`;
  $('#catalog-manufacturer').innerHTML=make('manufacturer','Select Manufacturer');
  $('#catalog-category').innerHTML=make('category','Select Category');
  $('#bill-region').innerHTML=make('region','Select Region');
  $('#bill-supplier').innerHTML=`<option value="">Select Supplier</option>${customers.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('')}`;
  $('#bill-employee').innerHTML=`<option value="">Select Employee</option>${users.map(x=>`<option value="${escapeHtml(x.name)}">${escapeHtml(x.name)}</option>`).join('')}`;
}
function renderCatalogV41(){
  $$('#catalog-tabs [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===catalogTab));
  const heading=catalogLabels[catalogTab],singular=catalogSingular[catalogTab],q=($('#catalog-search').value||'').toLowerCase();
  $('#catalog-heading').textContent=heading;$('#add-catalog-item').textContent=`+ ${singular}`;$('#import-catalog').style.display=catalogTab==='product'?'':'none';
  if(catalogTab==='product'){
    const rows=catalogItems.filter(x=>(`${x.code||''} ${x.name||''} ${x.category||''}`).toLowerCase().includes(q));
    $('#catalog-table').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Code</th><th>Name</th><th>Category Name</th><th>Purchase Price</th><th>Location</th><th>Sale Price</th><th>Stock</th><th>Track</th><th>Active</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.code||'-')}</td><td><strong>${escapeHtml(x.name)}</strong></td><td>${escapeHtml(x.category||'-')}</td><td>${money(x.purchase)}</td><td>${escapeHtml(x.location||'-')}</td><td>${money(x.sale)}</td><td>${Number(x.stock||0)}</td><td>${x.track?'Yes':'No'}</td><td>${x.active===false?'No':'Yes'}</td><td><button class="table-action" onclick="deleteCatalogItem('${x.id}')">Delete</button></td></tr>`).join('')||`<tr><td colspan="10" class="empty-cell">No products available</td></tr>`}</tbody></table></div><div class="table-pager">Items per page: <b>50</b> &nbsp; ${rows.length} item(s)</div>`;
  }else{
    const rows=catalogEntities[catalogTab].filter(x=>x.name.toLowerCase().includes(q));
    $('#catalog-table').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Name</th><th>Created On</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${escapeHtml(x.name)}</strong></td><td>${x.createdAt.slice(0,10)}</td><td><button class="table-action" onclick="deleteCatalogEntity('${catalogTab}','${x.id}')">Delete</button></td></tr>`).join('')||`<tr><td colspan="3" class="empty-cell">No ${heading.toLowerCase()} available</td></tr>`}</tbody></table></div><div class="table-pager">Items per page: <b>50</b> &nbsp; ${rows.length} item(s)</div>`;
  }
  fillCatalogSelects();
}
$('#catalog-search').oninput=renderCatalogV41;$('#catalog-search-button').onclick=renderCatalogV41;
$('#add-catalog-item').onclick=()=>{if(catalogTab==='product'){fillCatalogSelects();$('#catalog-dialog').showModal()}else{$('#catalog-entity-title').textContent=`Add ${catalogSingular[catalogTab]}`;$('#catalog-entity-name').value='';$('#catalog-entity-dialog').showModal()}};
$('#catalog-entity-form').onsubmit=e=>{e.preventDefault();catalogEntities[catalogTab].unshift({id:crypto.randomUUID(),name:$('#catalog-entity-name').value.trim(),createdAt:new Date().toISOString()});store.set('ag_catalog_entities',catalogEntities);e.target.reset();$('#catalog-entity-dialog').close();renderCatalogV41();toast(`${catalogSingular[catalogTab]} saved`)};
window.deleteCatalogEntity=(type,id)=>{if(confirm(`Delete this ${catalogSingular[type].toLowerCase()}?`)){catalogEntities[type]=catalogEntities[type].filter(x=>x.id!==id);store.set('ag_catalog_entities',catalogEntities);renderCatalogV41()}};
$('#catalog-form').onsubmit=e=>{e.preventDefault();catalogItems.unshift({id:crypto.randomUUID(),name:$('#catalog-name').value.trim(),code:$('#catalog-code').value.trim(),barcode:$('#catalog-barcode').value.trim(),manufacturer:$('#catalog-manufacturer').value,category:$('#catalog-category').value,location:$('#catalog-location').value.trim(),hsCode:$('#catalog-hs-code').value.trim(),hsValue:$('#catalog-hs-value').value.trim(),uom:$('#catalog-uom').value,purchase:+$('#catalog-purchase').value,sale:+$('#catalog-sale').value,purchaseAccount:$('#catalog-purchase-account').value,saleAccount:$('#catalog-sale-account').value,fbrSaleType:$('#catalog-fbr-sale-type').value,fbrRate:+$('#catalog-fbr-rate').value,sro:$('#catalog-sro').value,sroItem:$('#catalog-sro-item').value,track:$('#catalog-track').checked,active:$('#catalog-active').checked,stock:0,description:$('#catalog-description').value});store.set('ag_catalog_items',catalogItems);e.target.reset();$('#catalog-active').checked=true;$('#catalog-sale-purchase').checked=true;$('#catalog-dialog').close();catalogTab='product';renderCatalogV41();toast('Product added successfully')};

const billingNav=[['new-bill','Billing'],['expenses','Expenses'],['purchase-orders','Purchase Order'],['debit-notes','Debit Notes'],['recurring-bills','Recurring Bills'],['make-payments','Make Payment']];
function renderBillingTabs(){const active=$('.view.active')?.id;$$('.billing-tabs').forEach(el=>el.innerHTML=billingNav.map(([id,label])=>`<button class="${active===id||(active==='bills'&&id==='new-bill')?'active':''}" onclick="showView('${id}')">${label}</button>`).join(''))}
function searchPanel(placeholder){return `<div class="panel search-panel"><h2>Search</h2><div class="search-grid"><label>${placeholder}<input class="billing-query" placeholder="Search..."></label><label>Start Date<input class="billing-start" type="date"></label><label>End Date<input class="billing-end" type="date"></label><label>Status<select class="billing-status"><option value="">All</option><option>Draft</option><option>Approved</option><option>Completed</option></select></label><button class="primary billing-search">Search</button></div></div>`}
function listPanel(title,buttonText,rows,columns,type){return `${searchPanel(`${title} No, Supplier, Total`)}<div class="panel"><div class="panel-head"><h2>${title}</h2><button class="primary" onclick="openBillingEntry('${type}')">+ ${buttonText}</button></div><div class="table-summary">${title} Total: <b>${money(rows.reduce((s,x)=>s+(+x.amount||+x.total||0),0))}</b></div><div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}<th>Status</th><th>Manage</th></tr></thead><tbody>${rows.map(x=>`<tr>${columns.map(c=>`<td>${c[1](x)}</td>`).join('')}<td><span class="badge approved">${escapeHtml(x.status||'Approved')}</span></td><td><button class="table-action" onclick="deleteBillingEntry('${type}','${x.id}')">Delete</button></td></tr>`).join('')||`<tr><td colspan="${columns.length+2}" class="empty-cell">No records available</td></tr>`}</tbody></table></div><div class="table-pager">Items per page: <b>50</b> &nbsp; ${rows.length} record(s)</div></div>`}
function renderBills(){const cols=[['Bill No.',x=>escapeHtml(x.number)],['Supplier',x=>escapeHtml(x.supplier)],['Bill Date',x=>x.date],['Bill Total',x=>money(x.total)],['Tax',x=>money(x.tax)],['Balance',x=>money(x.total)]];$('#bill-list-screen').innerHTML=listPanel('Bills','Bill',bills,cols,'bill')}
function renderPurchaseOrders(){const cols=[['PO No.',x=>escapeHtml(x.reference)],['Supplier',x=>escapeHtml(x.supplier)],['PO Date',x=>x.date],['Due Date',x=>x.dueDate||'-'],['Total',x=>money(x.amount)]];$('#po-list-screen').innerHTML=listPanel('Purchase Orders','Purchase Order',purchaseOrders,cols,'purchase-order')}
function renderDebitNotes(){const cols=[['Debit Note No.',x=>escapeHtml(x.reference)],['Supplier',x=>escapeHtml(x.supplier)],['Date',x=>x.date],['Debit Note Total',x=>money(x.amount)],['Balance',x=>money(x.amount)]];$('#debit-list-screen').innerHTML=listPanel('Debit Notes','Debit Note',debitNotes,cols,'debit-note')}
function renderRecurringBills(){const cols=[['Supplier Name',x=>escapeHtml(x.supplier)],['Start Date',x=>x.date],['Bill Total',x=>money(x.amount)],['Frequency',x=>x.frequency||'Monthly']];$('#recurring-list-screen').innerHTML=listPanel('Recurring Bills','Recurring',recurringBills,cols,'recurring-bill')}
function renderSupplierPayments(){const cols=[['Reference No.',x=>escapeHtml(x.reference)],['Supplier',x=>escapeHtml(x.supplier)],['Payment Date',x=>x.date],['Payment Account',x=>x.account||'Bank'],['Payment Amount',x=>money(x.amount)],['Balance',x=>money(0)]];$('#supplier-payment-screen').innerHTML=listPanel('Payments','Payment',supplierPayments,cols,'supplier-payment')}
function addBillItem(data={description:'',qty:1,price:0,taxRate:0,account:''}){const row=document.createElement('tr');row.className='bill-item-row';row.innerHTML=`<td><input class="bill-desc" placeholder="Item / Description" value="${escapeHtml(data.description)}"></td><td><input class="bill-qty" type="number" min="0.01" step=".01" value="${data.qty}"></td><td><input class="bill-price" type="number" min="0" step=".01" value="${data.price}"></td><td><select class="bill-account"><option value="">Search Account</option><option>Inventory / Purchases</option><option>Office Expense</option><option>Utilities Expense</option><option>Project Expense</option></select></td><td><select class="bill-tax-rate"><option value="0">No Tax</option><option value="5">5%</option><option value="16">16%</option><option value="18">18%</option></select></td><td class="bill-row-tax">0.00</td><td class="bill-row-net">0.00</td><td><button type="button" class="bill-row-add" title="Add row">+</button><button type="button" class="bill-row-remove" title="Remove row">×</button></td>`;row.querySelector('.bill-tax-rate').value=String(data.taxRate||0);row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calculateBill));row.querySelector('.bill-row-add').onclick=()=>addBillItem();row.querySelector('.bill-row-remove').onclick=()=>{row.remove();if(!$('#bill-items-body').children.length)addBillItem();calculateBill()};$('#bill-items-body').append(row);calculateBill()}
function calculateBill(){let subtotal=0,taxTotal=0;const inclusive=$('#bill-tax-inclusive').checked;$$('.bill-item-row').forEach(row=>{const qty=+row.querySelector('.bill-qty').value||0,price=+row.querySelector('.bill-price').value||0,rate=+row.querySelector('.bill-tax-rate').value||0,gross=qty*price;let base,tax;if(inclusive&&rate){base=gross/(1+rate/100);tax=gross-base}else{base=gross;tax=base*rate/100}subtotal+=base;taxTotal+=tax;row.querySelector('.bill-row-tax').textContent=tax.toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2});row.querySelector('.bill-row-net').textContent=(base+tax).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2})});$('#bill-subtotal').textContent=money(subtotal);$('#bill-tax-total').textContent=money(taxTotal);$('#bill-gross-total').textContent=money(subtotal+taxTotal);return{subtotal,tax:taxTotal,total:subtotal+taxTotal}}
function resetBillForm(){const form=$('#bill-form');form.reset();$('#bill-date').value=today();const due=new Date();due.setDate(due.getDate()+14);$('#bill-due-date').value=due.toISOString().slice(0,10);$('#bill-items-body').innerHTML='';addBillItem();addBillItem();fillCatalogSelects()}
$('#bill-tax-inclusive').onchange=calculateBill;$('#bill-add-contact').onclick=()=>{$('#customer-dialog').showModal()};$('#bill-date').value=today();$('#bill-form').onsubmit=e=>{e.preventDefault();saveBill('Approved')};$('#save-bill-draft').onclick=()=>saveBill('Draft');
function saveBill(status){if(!$('#bill-form').reportValidity())return;const supplier=customers.find(x=>String(x.id)===String($('#bill-supplier').value)),items=$$('.bill-item-row').map(row=>({description:row.querySelector('.bill-desc').value,qty:+row.querySelector('.bill-qty').value||0,price:+row.querySelector('.bill-price').value||0,account:row.querySelector('.bill-account').value,taxRate:+row.querySelector('.bill-tax-rate').value||0})).filter(x=>x.description||x.qty*x.price);if(!items.length)return toast('Add at least one bill item');const totals=calculateBill();bills.unshift({id:crypto.randomUUID(),supplier:supplier?.name||$('#bill-supplier').selectedOptions[0]?.text||'',supplierId:$('#bill-supplier').value,number:$('#bill-number').value,reference:$('#bill-reference').value,date:$('#bill-date').value,dueDate:$('#bill-due-date').value,employee:$('#bill-employee').value,region:$('#bill-region').value,items,taxInclusive:$('#bill-tax-inclusive').checked,...totals,status,notes:$('#bill-notes').value});store.set('ag_bills',bills);resetBillForm();toast(`Bill saved as ${status}`);showView('bills')}
window.openBillingEntry=type=>{billingEntryType=type;const names={'purchase-order':'Purchase Order','debit-note':'Debit Note','recurring-bill':'Recurring Bill','supplier-payment':'Payment',bill:'Bill'};$('#billing-entry-title').textContent=`New ${names[type]}`;$('#billing-entry-date').value=today();$('#billing-entry-dialog').showModal()};
$('#billing-entry-form').onsubmit=e=>{e.preventDefault();const item={id:crypto.randomUUID(),reference:$('#billing-entry-reference').value,supplier:$('#billing-entry-supplier').value,date:$('#billing-entry-date').value,amount:+$('#billing-entry-amount').value,status:$('#billing-entry-status').value};const map={'purchase-order':[purchaseOrders,'ag_purchase_orders'],'debit-note':[debitNotes,'ag_debit_notes'],'recurring-bill':[recurringBills,'ag_recurring_bills'],'supplier-payment':[supplierPayments,'ag_supplier_payments']};const target=map[billingEntryType];if(target){target[0].unshift(item);store.set(target[1],target[0])}e.target.reset();$('#billing-entry-dialog').close();renderBusinessModules();toast('Entry saved')};
window.deleteBillingEntry=(type,id)=>{if(!confirm('Delete this record?'))return;const map={'bill':[bills,'ag_bills'],'purchase-order':[purchaseOrders,'ag_purchase_orders'],'debit-note':[debitNotes,'ag_debit_notes'],'recurring-bill':[recurringBills,'ag_recurring_bills'],'supplier-payment':[supplierPayments,'ag_supplier_payments']};const pair=map[type];const updated=pair[0].filter(x=>x.id!==id);if(type==='bill')bills=updated;if(type==='purchase-order')purchaseOrders=updated;if(type==='debit-note')debitNotes=updated;if(type==='recurring-bill')recurringBills=updated;if(type==='supplier-payment')supplierPayments=updated;store.set(pair[1],updated);renderBusinessModules()};

function renderInvoicesV41(){const q=($('#invoice-search').value||'').toLowerCase(),start=$('#invoice-search-start').value,end=$('#invoice-search-end').value,status=$('#invoice-search-status').value;const rows=invoices.filter(i=>(`${i.number} ${i.customer.name} ${i.total}`).toLowerCase().includes(q)&&(!start||i.issueDate>=start)&&(!end||i.issueDate<=end)&&(!status||i.status===status));$('#invoice-summary').innerHTML=`Invoice Total: <b>${money(rows.reduce((s,i)=>s+i.total,0))}</b> &nbsp; TAX: <b>${money(rows.reduce((s,i)=>s+i.tax,0))}</b> &nbsp; Balance: <b>${money(rows.reduce((s,i)=>s+i.total,0)-payments.reduce((s,p)=>s+p.amount,0))}</b>`;$('#invoice-table').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Invoice No.</th><th>Customer</th><th>Invoice Date</th><th>Invoice Total</th><th>TAX</th><th>Balance</th><th>Status</th><th>Manage</th></tr></thead><tbody>${rows.map(i=>`<tr><td><button class="link" onclick="viewInvoice('${i.id}')">${escapeHtml(i.number)}</button></td><td>${escapeHtml(i.customer.name)}</td><td>${i.issueDate}</td><td>${money(i.total)}</td><td>${money(i.tax)}</td><td>${money(Math.max(0,i.total-payments.filter(p=>p.invoiceId===i.id).reduce((s,p)=>s+p.amount,0)))}</td><td><span class="badge ${i.status.toLowerCase().replaceAll(' ','-')}">${i.status}</span></td><td><button class="table-action" onclick="viewInvoice('${i.id}')">View</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty-cell">No invoices available</td></tr>'}</tbody></table></div><div class="table-pager">Items per page: <b>50</b> &nbsp; ${rows.length} invoice(s)</div>`}
renderInvoices=renderInvoicesV41;$('#invoice-search').oninput=renderInvoicesV41;$('#invoice-search-button').onclick=renderInvoicesV41;$('#invoice-search-status').onchange=renderInvoicesV41;

function renderExpensesV41(){const start=$('#expense-search-start').value,end=$('#expense-search-end').value;const rows=expenses.filter(x=>(!start||x.date>=start)&&(!end||x.date<=end));$('#expense-table').innerHTML=`<div class="table-summary">Expense Total: <b>${money(rows.reduce((s,x)=>s+(+x.amount||0),0))}</b></div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Reference #</th><th>Paid Through</th><th>Customer / Detail</th><th>Total Expense</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td>${escapeHtml(x.reference||x.id.slice(0,8))}</td><td>${escapeHtml(x.paymentAccount||'Bank')}</td><td><strong>${escapeHtml(x.title)}</strong><br><small>${escapeHtml(x.category||'')}</small></td><td>${money(x.amount)}</td><td><strong>${money(x.amount)}</strong></td><td><span class="badge approved">Recorded</span></td><td class="actions"><button onclick="previewExpense('${x.id}')">Preview</button><button onclick="editExpense('${x.id}')">Edit</button><button onclick="deleteExpense('${x.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty-cell">No expenses available</td></tr>'}</tbody></table></div><div class="table-pager">Items per page: <b>50</b> &nbsp; ${rows.length} expense(s)</div>`}
renderExpenses=renderExpensesV41;$('#expense-search-button').onclick=renderExpensesV41;
window.previewExpense=id=>{const x=expenses.find(e=>String(e.id)===String(id));if(!x)return;alert(`EXPENSE PREVIEW\n\nDate: ${x.date}\nReference: ${x.reference||String(x.id).slice(0,8)}\nExpense: ${x.title}\nCategory: ${x.category||'-'}\nPaid Through: ${x.paymentAccount||'Bank'}\nAmount: ${money(x.amount)}\nNotes: ${x.notes||'-'}`)};

function fbrTabs(active){return `<div class="module-top-tabs"><button class="${active==='submit'?'active':''}" onclick="showView('fbr-submit')">Tax Invoices</button><button class="${active==='submitted'?'active':''}" onclick="showView('fbr-submitted')">Submitted Tax</button><button onclick="showView('fbr-settings')">FBR Settings</button></div>`}
function renderFbr(){
  $$('#fbr-submit .fbr-tabs').forEach(x=>x.innerHTML=fbrTabs('submit'));$$('#fbr-submitted .fbr-tabs').forEach(x=>x.innerHTML=fbrTabs('submitted'));
  const eligible=invoices.filter(i=>i.invoiceType==='FBR'&&i.taxType==='GST'&&i.fbrStatus!=='SUBMITTED'),submitted=invoices.filter(i=>i.invoiceType==='FBR'&&i.fbrStatus==='SUBMITTED');
  $('#fbr-submit-screen').innerHTML=`${searchPanel('Invoice No, Customer, Invoice Total')}<div class="panel"><div class="panel-head"><h2>Tax Invoices</h2><span class="muted">Open an invoice to validate and submit it</span></div><div class="table-scroll"><table><thead><tr><th>Invoice No.</th><th>Customer</th><th>Invoice Date</th><th>Invoice Total</th><th>Tax</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>${eligible.map(i=>`<tr><td><button class="link" onclick="viewInvoice('${i.id}')">${escapeHtml(i.number)}</button></td><td>${escapeHtml(i.customer.name)}</td><td>${i.issueDate}</td><td>${money(i.total)}</td><td>${money(i.tax)}</td><td>${money(i.total)}</td><td>${escapeHtml(i.fbrStatus||'Pending')}</td><td><button class="table-action" onclick="viewInvoice('${i.id}')">View Invoice</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty-cell">No invoices ready for submission</td></tr>'}</tbody></table></div></div>`;
  $('#fbr-submitted-screen').innerHTML=`${searchPanel('Invoice No, Customer, Invoice Total')}<div class="panel"><h2>Submitted Tax Invoices</h2><div class="table-scroll"><table><thead><tr><th>Invoice No.</th><th>Customer</th><th>Invoice Date</th><th>Invoice Total</th><th>Tax</th><th>Balance</th><th>FBR Status</th></tr></thead><tbody>${submitted.map(i=>`<tr><td>${escapeHtml(i.number)}</td><td>${escapeHtml(i.customer.name)}</td><td>${i.issueDate}</td><td>${money(i.total)}</td><td>${money(i.tax)}</td><td>${money(i.total)}</td><td><span class="badge approved">Submitted</span></td></tr>`).join('')||'<tr><td colspan="7" class="empty-cell">No submitted tax invoices</td></tr>'}</tbody></table></div><div class="table-pager">${submitted.length} submitted invoice(s)</div></div>`;
}

function renderBusinessModules(){renderBillingTabs();renderCatalogV41();renderBills();renderPurchaseOrders();renderDebitNotes();renderRecurringBills();renderSupplierPayments();renderInvoicesV41();renderExpensesV41();renderFbr()}
const v40RenderAll=renderAll;renderAll=function(){v40RenderAll();renderBusinessModules()};
if(!$('#bill-items-body').children.length)resetBillForm();
renderBusinessModules();
