let expenseCategories=[],documents=[];
titles.documents=['Invoice Automation','Upload, OCR, Google Drive and transaction register'];
const mapPayment=p=>({id:String(p.id),invoiceId:String(p.invoice),invoiceNumber:p.invoice_number,customer:p.customer_name,amount:+p.amount,date:p.payment_date,method:p.method,reference:p.reference});
const mapExpense=e=>({id:String(e.id),title:e.title,category:e.category_name,categoryId:e.category,amount:+e.amount,date:e.expense_date,notes:e.notes,vendor:e.vendor,project:e.project,expenseAccount:e.expense_account,paymentAccount:e.payment_account});
const mapProject=p=>({id:String(p.id),name:p.name,customer:{id:String(p.customer),name:p.customer_name},category:p.category,budget:+p.budget,status:{PLANNED:'Planned',ACTIVE:'Active',HOLD:'On Hold',COMPLETED:'Completed',CANCELLED:'Cancelled'}[p.status]||p.status,deadline:p.deadline,invoiced:+p.invoiced,expenseTotal:+p.expense_total,profitability:+p.profitability,tasks:p.tasks});
async function loadPhase23(){if(!apiToken())return;try{const staff=getSession()?.role==='Employee';if(staff){const [prs,docs]=await Promise.all([api('/projects/'),api('/documents/')]);payments=[];expenses=[];expenseCategories=[];projects=listResults(prs).map(mapProject);documents=listResults(docs);renderAll();renderDocuments();await refreshDriveStatus();return}const [ps,es,prs,cats,docs,summary]=await Promise.all([api('/payments/'),api('/expenses/'),api('/projects/'),api('/expense-categories/'),api('/documents/'),api('/reports/dashboard/')]);payments=listResults(ps).map(mapPayment);expenses=listResults(es).map(mapExpense);projects=listResults(prs).map(mapProject);expenseCategories=listResults(cats);documents=listResults(docs);renderAll();renderDocuments();renderApiReport(summary);await refreshDriveStatus()}catch(error){toast(error.message)}}
const originalLoadPhaseOne=loadPhaseOne;loadPhaseOne=async()=>{await originalLoadPhaseOne();await loadPhase23()};
const paidForInvoice=id=>payments.filter(p=>String(p.invoiceId)===String(id)).reduce((sum,p)=>sum+p.amount,0);
renderPayments=()=>{const options=invoices.filter(i=>!['Paid','Cancelled'].includes(i.status)).map(i=>{const remaining=Math.max(0,i.total-paidForInvoice(i.id));return `<option value="${i.id}" data-remaining="${remaining}">${i.number} — ${escapeHtml(i.customer.name)} — Due ${money(remaining)}</option>`}).join('');$('#payment-invoice').innerHTML='<option value="">Choose unpaid invoice...</option>'+options;$('#payment-table').innerHTML=payments.length?`<table><thead><tr><th>Date</th><th>Invoice</th><th>Customer</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${p.date}</td><td>${escapeHtml(p.invoiceNumber)}</td><td>${escapeHtml(p.customer)}</td><td>${p.method}</td><td>${escapeHtml(p.reference||'—')}</td><td><strong>${money(p.amount)}</strong></td></tr>`).join('')}</tbody></table>`:'<div style="padding:28px;text-align:center;color:#6c768b">No payments recorded.</div>'};
$('#payment-invoice').onchange=()=>{const remaining=+($('#payment-invoice').selectedOptions[0]?.dataset.remaining||0);$('#payment-amount').max=remaining||'';if(remaining)$('#payment-amount').value=remaining};
$('#payment-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter,invoice=$('#payment-invoice').value,amount=+$('#payment-amount').value,remaining=+($('#payment-invoice').selectedOptions[0]?.dataset.remaining||0);if(!invoice)return toast('Please choose an unpaid invoice');if(amount<=0||amount>remaining)return toast(`Payment must be between PKR 1 and ${money(remaining)}`);const payload={invoice:+invoice,amount:String(amount),payment_date:$('#payment-date').value,method:$('#payment-method').value,reference:$('#payment-reference').value,notes:''};if($('#payment-deposit-account').value)payload.deposit_account=+$('#payment-deposit-account').value;button.disabled=true;button.textContent='Saving...';try{await api('/payments/',{method:'POST',body:JSON.stringify(payload)});e.target.reset();paymentDialog.close();await Promise.all([loadPhaseOne(),loadAccounting()]);toast('Done! Payment and accounting entry saved')}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Save Payment'}};
$('#expense-form').onsubmit=async e=>{e.preventDefault();try{const categoryName=$('#expense-new-category').value.trim()||$('#expense-category').value;let category=expenseCategories.find(c=>c.name.toLowerCase()===categoryName.toLowerCase());if(!category)category=await api('/expense-categories/',{method:'POST',body:JSON.stringify({name:categoryName,description:'Manually added'})});const payload={title:$('#expense-title').value,category:category.id,amount:$('#expense-amount').value,expense_date:$('#expense-date').value,vendor:'',notes:$('#expense-notes').value};if($('#expense-ledger-account').value)payload.expense_account=+$('#expense-ledger-account').value;if($('#expense-payment-account').value)payload.payment_account=+$('#expense-payment-account').value;await api('/expenses/',{method:'POST',body:JSON.stringify(payload)});e.target.reset();expenseDialog.close();await Promise.all([loadPhase23(),loadAccounting()]);toast(`Done! Expense and accounting entry saved under ${categoryName}`)}catch(error){toast(error.message)}};
$('#project-form').onsubmit=async e=>{e.preventDefault();try{const category=$('#project-new-category').value.trim()||$('#project-category').value;await api('/projects/',{method:'POST',body:JSON.stringify({name:$('#project-name').value,customer:+$('#project-customer').value,category,budget:$('#project-budget').value,status:{Planned:'PLANNED',Active:'ACTIVE','On Hold':'HOLD',Completed:'COMPLETED'}[$('#project-status').value],deadline:$('#project-deadline').value||null,notes:'',tasks:[]})});e.target.reset();projectDialog.close();await loadPhase23();toast(`Done! Project created under ${category}`)}catch(error){toast(error.message)}};
renderProjects=()=>{$('#project-list').innerHTML=projects.length?projects.map(p=>`<div class="customer-card project-card"><span class="badge ${p.status.toLowerCase().replaceAll(' ','-')}">${p.status}</span><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.customer.name)} · ${escapeHtml(p.category)}</span><span>Budget: ${money(p.budget)}</span><span>Invoiced: ${money(p.invoiced)} · Cost: ${money(p.expenseTotal)}</span><span class="${p.profitability>=0?'green':'orange'}">Profitability: ${money(p.profitability)}</span><span>Deadline: ${p.deadline||'Not set'}</span></div>`).join(''):'<p>No projects yet.</p>'};
function renderApiReport(s){$('#report-revenue').textContent=money(s.revenue);$('#report-expenses').textContent=money(s.expenses);$('#report-net').textContent=money(s.net_profit);$('#report-projects').textContent=s.active_projects;$('#dash-overdue').textContent=s.overdue_invoices;$('#dash-due-soon').textContent=s.due_soon;$('#dash-uploaded-total').textContent=money(s.uploaded_transaction_total);$('#dash-uploaded-count').textContent=s.uploaded_document_count;$('#dash-pending-docs').textContent=s.pending_documents;$('#dash-top-customer').textContent=s.top_customer;$('#monthly-report').innerHTML=`<table><tbody><tr><th>Revenue</th><td>${money(s.revenue)}</td></tr><tr><th>Uploaded transaction total</th><td>${money(s.uploaded_transaction_total)}</td></tr><tr><th>Expenses</th><td>${money(s.expenses)}</td></tr><tr><th>Net Profit</th><td>${money(s.net_profit)}</td></tr><tr><th>Outstanding</th><td>${money(s.outstanding)}</td></tr><tr><th>Invoices</th><td>${s.invoice_count}</td></tr></tbody></table>`}
function reportQuery(){const params=new URLSearchParams(),start=$('#report-start')?.value,end=$('#report-end')?.value;if(start)params.set('start',start);if(end)params.set('end',end);return params.toString()?`?${params}`:''}
window.applyReportFilter=async()=>{const status=$('#report-download-status');try{status.textContent='Loading report data...';const summary=await api(`/reports/dashboard/${reportQuery()}`);renderApiReport(summary);status.textContent=`Report updated ${new Date().toLocaleString()}`}catch(error){status.textContent=error.message;toast(error.message)}};
window.downloadReport=async format=>{const status=$('#report-download-status');try{status.textContent=`Preparing ${format.toUpperCase()} report...`;const response=await fetch(`${API_BASE}/reports/export/${format}/${reportQuery()}`,{headers:{Authorization:`Token ${apiToken()}`}});if(!response.ok){const error=await response.json().catch(()=>({detail:'Report download failed.'}));throw new Error(apiError(error))}const blob=await response.blob();if(!blob.size)throw new Error('Downloaded report is empty.');const url=URL.createObjectURL(blob),a=document.createElement('a'),date=new Date().toISOString().slice(0,10);a.href=url;a.download=`ample-global-business-report-${date}.${format}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=`${format.toUpperCase()} report downloaded successfully.`;toast('Report downloaded successfully')}catch(error){status.textContent=error.message;toast(error.message)}};
const documentDialog=$('#document-dialog');$('#add-document').onclick=()=>{renderDocumentLinks();documentDialog.showModal()};
function renderDocumentLinks(){$('#document-customer').innerHTML='<option value="">None</option>'+customers.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');$('#document-project').innerHTML='<option value="">None</option>'+projects.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('')}
$('#document-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter,form=new FormData();form.append('title',$('#document-title').value);form.append('file',$('#document-file').files[0]);if($('#document-customer').value)form.append('customer',$('#document-customer').value);if($('#document-project').value)form.append('project',$('#document-project').value);button.disabled=true;button.textContent='Uploading...';try{const response=await fetch(`${API_BASE}/documents/`,{method:'POST',headers:{Authorization:`Token ${apiToken()}`},body:form});if(!response.ok){const detail=await response.json().catch(()=>({detail:'Document upload failed.'}));throw new Error(apiError(detail))}const saved=await response.json();e.target.reset();documentDialog.close();await loadPhase23();toast(`Done! Document uploaded ${new Date(saved.created_at).toLocaleString()}`)}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Upload & Start OCR'}};
function renderDocuments(){const origin=new URL(API_BASE).origin;$('#document-table').innerHTML=documents.length?`<table><thead><tr><th>Document / Uploaded</th><th>OCR / Transaction</th><th>Parties & Banks</th><th>Purpose / Category</th><th>Google</th><th>Actions</th></tr></thead><tbody>${documents.map(d=>{const x=d.extracted_data||{},missing=x.missing_fields||[];return `<tr><td><strong>${escapeHtml(d.title)}</strong><br><small>${new Date(d.created_at).toLocaleString()}</small><br><a href="${d.file.startsWith('/')?origin+d.file:d.file}" target="_blank">Open file</a>${d.ocr_status==='COMPLETED'?'<br><span class="badge approved">DONE</span>':''}</td><td><span class="badge ${d.ocr_status.toLowerCase()}">${d.ocr_status}</span><br><small><b>${escapeHtml(x.document_type||'Waiting')}</b><br>${escapeHtml(x.transaction_date||x.date||'-')} ${escapeHtml(x.transaction_time||'')}<br>Ref: ${escapeHtml(x.reference_number||'-')}<br>Invoice: ${escapeHtml(x.invoice_number||'-')}</small>${d.ocr_error?`<br><small>${escapeHtml(d.ocr_error)}</small>`:''}</td><td><small><b>Vendor:</b> ${escapeHtml(x.vendor||'-')}<br><b>From:</b> ${escapeHtml(x.sender||'-')}<br>${escapeHtml(x.sender_bank||'')}<br><b>To:</b> ${escapeHtml(x.receiver||'-')}<br>${escapeHtml(x.receiver_bank||'')}</small></td><td><b>${escapeHtml(x.category||'Waiting')}</b><br><small>${escapeHtml(x.purpose||'OCR will detect purpose')}<br>${escapeHtml(x.description||'')}</small><br>${x.amount?money(x.amount):''}${missing.length?`<br><span class="badge draft">Review: ${escapeHtml(missing.join(', '))}</span>`:''}</td><td>${d.drive_web_link?`<a href="${d.drive_web_link}" target="_blank">Drive ✓</a>`:'Drive -'}<br><span class="badge ${d.sheet_sync_status==='SYNCED'?'approved':'draft'}">Sheet: ${d.sheet_sync_status}</span></td><td class="actions"><button onclick="retryOCR('${d.id}')">Retry OCR</button><button onclick="syncDrive('${d.id}')">Drive</button><button onclick="syncSheet('${d.id}')">Sheet</button></td></tr>`}).join('')}</tbody></table>`:'<div style="padding:28px;text-align:center;color:#6c768b">No documents uploaded.</div>'}
window.retryOCR=async id=>{try{await api(`/documents/${id}/retry_ocr/`,{method:'POST',body:'{}'});toast('OCR queued');setTimeout(loadPhase23,1200)}catch(error){toast(error.message)}};
window.syncDrive=async id=>{try{await api(`/documents/${id}/sync_drive/`,{method:'POST',body:'{}'});await loadPhase23();toast('Synced to Google Drive')}catch(error){toast(error.message)}};
window.syncSheet=async id=>{try{await api(`/documents/${id}/sync_sheet/`,{method:'POST',body:'{}'});await loadPhase23();toast('Invoice data added to Google Sheet')}catch(error){toast(error.message)}};
$('#connect-drive').onclick=async()=>{try{const result=await api('/drive/authorize/');location.href=result.authorization_url}catch(error){toast(error.message)}};
$('#browse-drive').onclick=async()=>{try{const files=await api('/drive/files/');$('#drive-browser').innerHTML=`<div class="panel" style="margin:16px 0"><h3>Google Drive files</h3>${files.length?files.map(f=>`<div class="list-row"><span>${escapeHtml(f.name)}</span><span><a href="${f.webViewLink||'#'}" target="_blank">Open</a> <select id="drive-doc-${f.id}"><option value="">Link to local document...</option>${documents.map(d=>`<option value="${d.id}">${escapeHtml(d.title)}</option>`).join('')}</select> <button onclick="linkDriveFile('${f.id}')">Link</button></span></div>`).join(''):'<p>No accessible Drive files.</p>'}</div>`}catch(error){toast(error.message)}};
window.linkDriveFile=async fileId=>{const docId=$(`#drive-doc-${fileId}`).value;if(!docId)return toast('Select a local document first');try{await api(`/documents/${docId}/link_drive/`,{method:'POST',body:JSON.stringify({file_id:fileId})});await loadPhase23();toast('Drive file linked')}catch(error){toast(error.message)}};
async function refreshDriveStatus(){try{const s=await api('/drive/status/');$('#drive-status').innerHTML=s.connected?`<span class="badge approved">Google connected</span> <span class="badge ${s.sheets_configured?'approved':'draft'}">Google Sheet ${s.sheets_configured?'configured':'needs Sheet ID'}</span>`:'<span class="badge draft">Google not connected</span>'}catch{}}
if(apiToken())loadPhase23();
